version: '3.8'

services:
  # === BASE DE DONNÉES POUR AUTEUR ===
  auteur-db:
    image: postgres:15
    container_name: auteur-db
    environment:
      POSTGRES_DB: auteurdb              # Nom de la base de données
      POSTGRES_USER: postgres            # Nom d'utilisateur
      POSTGRES_PASSWORD: postgres        # Mot de passe
    ports:
      - "5433:5432"                      # Port machine hôte : port du container
    volumes:
      - auteur-data:/var/lib/postgresql/data  # Volume pour persister les données
    networks:
      - library-network                  # Réseau Docker partagé

  # === SERVICE SPRING BOOT AUTEUR ===
  auteur-service:
    build:
      context: ./auteur-service          # Dossier contenant le Dockerfile
    container_name: auteur-service
    ports:
      - "8081:8081"                      # Port exposé du microservice
    depends_on:
      - auteur-db                        # On attend que la BDD soit prête avant de démarrer ce service
    networks:
      - library-network

# === VOLUMES ===
# Volume pour conserver les données de la base même après arrêt du container
volumes:
  auteur-data:

# === RÉSEAU DOCKER COMMUN ===
# Permet aux services de communiquer entre eux (auteur-service <-> auteur-db)
networks:
  library-network:
    driver: bridge
